spring:
  profiles:
    active: dev
  application:
    name: order-service
  cloud:
    config:
      uri: http://localhost:8888/
      label: main
  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

